---
title: "Talks"
---

<br>

####2023: 

- (Mit Sarah Ihden): Expressing future reference in Middle Low German – a corpus-based approach. Workshop [Futures of the Past](futures-of-the-past.phil.hhu.de/) at HHU Düsseldorf, Haus der Universität, March 7-8, 2023.


####2022: 

- (Mit Stefan Hartmann): Futurkonstruktionen im Wandel: werden + Infinitiv und Konkurrenzmuster aus konstruktionsgrammatischer Perspektive. Jahrestagung der gesellschaft für germanistische Sprachgeschichte 2023 in Dresden, September 30, 2022.

- (mit Stefan Hartmann): [Disentangling the constructional semantics of German future constructions](https://ichl.ling-phil.ox.ac.uk/abstracts/229). [International Conference on Historical Linguistics 2022](https://ichl.ling-phil.ox.ac.uk/) in Oxford, August 1, 2022.

####2021: 

- (Mit Ingrid Schröder und Sarah Ihden): Korpusdaten als Basis für eine neue mittelniederdeutsche Grammatik – Möglichkeiten und Herausforderungen. Workshop [„Quantitative und qualitative Methoden zur empirischen Erforschung grammatischer Strukturen in historischen Quellen“](https://oelt2021.univie.ac.at/angenommene-workshops/) im Rahmen der Österreichischen Linguistik-Tagung, Universität Wien (online), December 10–12, 2021.

<br>

####2018:


- Beschreibungsmöglichkeiten der derivationsmorphologischen Adaption mittelniederdeutscher Lehnwörter im Altnordischen. [„Regionale Varietäten früher und heute“ – 7. Nachwuchskolloquium des Vereins für niederdeutsche
Sprachforschung](https://igdd.org/7-nachwuchskolloquium-des-vnds-5-10-2018-paderborn/), Universität Paderborn, 04.-05. Oktober 2018. 

- Eingenordet – Morphologische Assimilation mittelniederdeutscher Lehnwörter im Altnordischen. ["Wie verändern wir Sprache?" Im Rahmen des Universitätskolleg 2.0 geförderte Studentische Tagung](https://www.slm.uni-hamburg.de/germanistik/studium/studium-forschung/lehrprojekt-sprachwandel/studentische-tagung.html). Organisation: Lisa Dücker, Melitta Gillmann, Eleonore Schmitt, Renata Szczepaniak, Annika Vieregge, Universität Hamburg, 1.-3. Februar 2018.